apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.service.name . }}
  labels:
    app: {{ tpl .Values.deployment.name . }}
spec:
  ports:
  - name: http
    port: 5432
    targetPort: 5432
  selector:
    app: {{ tpl .Values.deployment.name . }}
  type: {{ .Values.service.type }}